//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface FUFlightLocation : NSObject
{
    double x;
    double y;
    double theta;
    double psi;
}

@property double psi; // @synthesize psi;
@property double theta; // @synthesize theta;
@property double y; // @synthesize y;
@property double x; // @synthesize x;

@end

