//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#import <CoreLocation/CoreLocation.h>



@class FUFlightStep, NSString;

@interface FUFlightLeg : NSObject <NSCopying, NSSecureCoding>
{
    long long _status;
    double _duration;
    FUFlightStep *_departure;
    FUFlightStep *_arrival;
    double _heading;
    double _speed;
    double _altitude;
    NSString *_aircraftcode;
    CLLocationCoordinate2D _location;
}

+ (BOOL)supportsSecureCoding;
@property(retain) NSString *aircraftcode; // @synthesize aircraftcode=_aircraftcode;
@property struct CLLocationCoordinate2D location; // @synthesize location=_location;
@property double altitude; // @synthesize altitude=_altitude;
@property double speed; // @synthesize speed=_speed;
@property double heading; // @synthesize heading=_heading;
@property(retain) FUFlightStep *arrival; // @synthesize arrival=_arrival;
@property(retain) FUFlightStep *departure; // @synthesize departure=_departure;
@property double duration; // @synthesize duration=_duration;
@property long long status; // @synthesize status=_status;
//- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;

@end

