//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSUUID.h"

#import "CDStructures.h"

__attribute__((visibility("hidden")))
@interface FUFlightUpdateTicket : NSUUID
{
    CDUnknownBlockType _block;
}

@property(copy) CDUnknownBlockType block; // @synthesize block=_block;
//- (void).cxx_destruct;

@end

