//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface FUFlightViewController : NSViewController
{
}

- (id)initWithFlightCode:(unsigned long long)arg1 airlineCode:(id)arg2;

@end
