//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FUAirline;

__attribute__((visibility("hidden")))
@interface FUFlightCodeShare : NSObject
{
    FUAirline *_airline;
    long long _flightNumber;
}

@property long long flightNumber; // @synthesize flightNumber=_flightNumber;
@property(retain) FUAirline *airline; // @synthesize airline=_airline;
//- (void).cxx_destruct;

@end

